### ISSUE TITLE
Structured Logging - Refactor logging statements to address CA2254

### ISSUE THREAD

**Issue by aaronpowell** [Azure/data-api-builder#1517]
Currently we have a lot of [CA2254](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2254) warnings in the codebase due to how we generate log messages.

Here's an example:

```c#
_logger.LogInformation($"Using merged config file based on environment:{configToBeUsed}.");
```

The issue is that we're not using [log templates](https://learn.microsoft.com/dotnet/core/extensions/logging?tabs=command-line#log-message-template) which enable better structured logging.

Ideally, the code should be:

```c#
_logger.LogInformation("Using merged config file based on environment:{configToBeUsed}.", configToBeUsed);
```

NLog has a good overview on [structured logging](https://github.com/NLog/NLog/wiki/How-to-use-structured-logging).

This issue is to track the codebase-wide refactor.

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/data-api-builder/pull/1594
- [x] remove dupe exception logging
- [x] update service/config project
- [x] update core project
```

**Comment by aaronpowell** [comment]
Branching from https://github.com/Azure/data-api-builder/pull/1402#discussion_r1202762244

**Comment by seantleonard** [comment]
Whenever this is picked up, I would suggest and highly appreciate breaking up this refactor into multiple PRs to make reviewing quick and straightforward.

**Comment by aaronpowell** [comment]
Yep, we should create a feature branch and do PRs into that branch so it can be reviewed piece by piece.

**Comment by seantleonard** [comment]
As a follow up to #1541, which has tests that validates the logger logs the expected messages:
We can have more explicit validation of the logged messages:
1. This requires us to turn our message templates into constants with variables used for structured logging present within curly braces: `string messageTemplateError = "{runtimeConfigFile} does not exist."
2. Then, validate that the expected log message template is logged  (this value is available to us without having to run String.Contains() or String.Split()
3. Optionally validate that the expected variable value is used. in this example, the runtimeConfigFile value is as expected.

You can do this with the following (copied from my comment on `dotnet/runtime/issues/ 67577 #issuecomment-1625920776`):

-----------------------------------------------
> I think unit testing should be done using the interface (`IReadOnlyList<KeyValuePair<string, object>>`). I now think the most valid reason for these methods is for re-implementing your own log methods, not unit testing.

Your suggestion pointed me in the right direction (at least from my perspective in order to achieve the validation behavior I was seeking). I was attempting to validate the originally formatted error message, which contains variable(s) surrounded by curly brackets `{variable}` when using structured logging. The originally formatted error is present in FormattedLogValues collection.

I used examples other suggested for how to use Moq to verify the logging invocation, combined with a helper function to parse out and validate the key value pair contents:
```csharp
            loggerMock.Verify(
                x => x.Log(
                LogLevel.Error,
                It.IsAny<EventId>(),
                It.Is<It.IsAnyType>((o, t) => ValidateLoggedState(o, t)),
                It.IsAny<Exception?>(),
                (Func<It.IsAnyType, Exception?, string>)It.IsAny<object>()
                ),
                Times.Once
            );
```
and
```csharp
    public bool ValidateLoggedState(object o, Type t)
    {
        // Cast FormattedLogValues (internal class) to a list of key/value pairs.
        IReadOnlyList<KeyValuePair<string, object>> loggedValues = (IReadOnlyList<KeyValuePair<string, object>>)o;

        // Validate that a log with the expected message template is present.
        bool expectedErrorMsgTemplateExists = loggedValues.Any(kvp => kvp.Key == "{OriginalFormat}" && kvp.Value.ToString() == ErrorMessages.ERRMESSAGEFILEEXISTS);

        //Validate that the expected variable was used for filling the template.
        //For demonstration purposes since there may not be a point to doing this.
        bool formattedErrorMsgExists = loggedValues.Any(kvp => kvp.Key == "runtimeConfigFile");

        // Validation result.
        return expectedErrorMsgTemplateExists && formattedErrorMsgExists;
    }
```
