### ISSUE TITLE
[Enhancement] Multiple Mutations - Multiple Create

### ISSUE THREAD

**Issue by severussundar** [Azure/data-api-builder#1576]
Nested Mutation refers to the ability to perform mutation operations such as insert, update, and delete on a related entity in addition to the parent entity.

```[tasklist]
### Related items
- [ ] https://github.com/Azure/data-api-builder/issues/906
- [ ] #285
- [ ] #479
```

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/data-api-builder/issues/1698
- [ ] https://github.com/Azure/data-api-builder/issues/1701
- [ ] https://github.com/Azure/data-api-builder/issues/1889
- [ ] https://github.com/Azure/data-api-builder/issues/1700
- [ ] https://github.com/Azure/data-api-builder/issues/1887
- [ ] https://github.com/Azure/data-api-builder/issues/1699
- [ ] https://github.com/Azure/data-api-builder/issues/1950
- [ ] https://github.com/Azure/data-api-builder/issues/1951
- [ ] https://github.com/Azure/data-api-builder/issues/2022
- [ ] https://github.com/Azure/data-api-builder/issues/2024
- [ ] https://github.com/Azure/data-api-builder/issues/2025
- [ ] https://github.com/Azure/data-api-builder/issues/2018
- [ ] https://github.com/Azure/data-api-builder/issues/2026
- [ ] https://github.com/Azure/data-api-builder/issues/1948
- [ ] https://github.com/Azure/data-api-builder/issues/1930
- [ ] https://github.com/Azure/data-api-builder/issues/2023
- [ ] https://github.com/Azure/data-api-builder/issues/2132
- [ ] https://github.com/Azure/data-api-builder/issues/2157
- [ ] https://github.com/Azure/data-api-builder/issues/2148
```

<Under construction>

**Comment by seantleonard** [comment]
removing milestone as individual items are tracked on per-milestone basis.

**Comment by JerryNixon** [comment]
Done with this workstream. Individual items remain open.
