### ISSUE TITLE
Support hot reloading of configuration

### ISSUE THREAD

**Issue by JelteF** [Azure/data-api-builder#67]
Allow specifiying something like a `--watch` to make the runtime watch the provided configs and reload when they change.

Relevant comment from @jarupatj  in #50:
> You should look at using IOptionsMonitor
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-5.0#options-interfaces

#892 
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/data-api-builder/pull/1981
- [ ] https://github.com/Azure/data-api-builder/issues/1969
- [ ] https://github.com/Azure/data-api-builder/issues/1869
- [ ] https://github.com/Azure/data-api-builder/issues/1968
- [ ] https://github.com/Azure/data-api-builder/issues/1967
- [ ] https://github.com/Azure/data-api-builder/issues/1966
```

**Comment by aaronburtle** [comment]
Modified this issue to cove hot reloading of the configuration file. This will clear duplicate issues, which will all be tracked here.

**Comment by aaronburtle** [comment]
Would be great to have a switch on the CLI, something like --watch that will automatically reload the configuration file (and thus re-generate the in-memory schema) whenever the file is changed. Something like https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-watch

That would greatly improve development velocity.

**Comment by aaronburtle** [comment]
In order to set the LogLevel based on the mode in the runtimeconfig we need to use a configuration provider that can reload the configuration after updating the Loglevel.

More information can be found here: https://learn.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line

**Comment by aaronburtle** [comment]
Moved to April, waiting on new configuration resolver.

**Comment by michaelstaib** [comment]
Form the GraphQL side you need to implement an ITypeModule ... this will manage the phase out of schemas... 

Here you can see an example.
https://github.com/ChilliCream/graphql-platform/blob/13349fa4af03514507ed5e3aaf9a771c696b56a6/src/HotChocolate/Fusion/src/Core/DependencyInjection/FileWatcherTypeModule.cs

The TypeModule is registered with the schema.

**Comment by JerryNixon** [comment]
## Hot reload is supported _only_ when:
When "mode" == "development" then Supported.

**Comment by seantleonard** [comment]
hot-reload property in config?

**Comment by aaronburtle** [comment]
I have created a number of sub-tasks to help track the progress on Hot Reload.

Currently, we are refreshing the `RuntimeConfig` to match any updates that we see in the associated config file when we are in the local scenario and start the engine in developer mode.

To facilitate extending Hot Reload in the future, a refactor of the `RuntimeConfigProvider` is taking place

https://github.com/Azure/data-api-builder/issues/1966

as well as some changes to make hot reload work with the new multi config code

https://github.com/Azure/data-api-builder/issues/1967

Additionally, one of the key features we want support for hot reloading is reloading of the log-level, and so this property is being added to the config and we have a task to track being able to hot reload this property in both dev and production mode

https://github.com/Azure/data-api-builder/issues/1968

Additionally, there are some tasks for updating those settings which depend on the config only at startup, such as the OpenApiDoc and Auth settings

https://github.com/Azure/data-api-builder/issues/1869

https://github.com/Azure/data-api-builder/issues/1969

**Comment by seantleonard** [comment]
Moving this + hot reload related tasks to post GA -> tracking via 1.2rc milestone.

**Comment by seantleonard** [comment]
The top-level task tracking hot reload can remain in backlog as we address sub-tasks. Ideally a sprint's tracked work items should be resolvable. This task has so many pre-reqs , we need to resolve those first.
